---
name: Publish
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: actions/setup-node@v6
        with:
          node-version: '26'
          registry-url: https://registry.npmjs.org
      - run: npm install -g bob@5.0.1
      - run: npm install
      - run: bob publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
