---
name: Release Major
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: cliffano/release-action@v1.0.0
        with:
          release_type: 'major'
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
